### ISSUE TITLE
[Image-Size] Switching from Ubuntu to Alpine Linux?

### ISSUE THREAD

**Issue by Siassei** [kiview/docker-volume-backup#4]
Hey,

I will start an discussion to switch from Ubuntu to alpine linux. alpine provied all commands that are using by the script and needs much less space.
So, is it a reason to use ubuntu?

**Comment by kiview** [comment]
Hi @Siassei,
I'd be happy to switch to Alpine or Debian Slim if it works the same, would you like to contribute a PR? ;)

**Comment by Siassei** [comment]
is done. see #5 for more
